version: '3'

services:
  ampache:
    privileged: true
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    
    ports:
      - 80:80
    volumes:
      - /disks/Media:/disks/Media

      - sql:/var/lib/mysql
      - logs:/var/log/ampache
      - config:/var/www/config
      - sql_config:/etc/mysql
    
volumes:
  sql:
  logs:
  config:
  sql_config:
