version: '3'

services:
  ampache:
    privileged: true
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    
    expose:
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - /disks/Media:/disks/Media
      - /home/pi/ampache_docker/user_folder/:/home/usr
      - /etc/letsencrypt:/etc/letsencrypt

      - sql:/var/lib/mysql
      - logs:/var/log/ampache
      - config:/var/www/config
      - sql_config:/etc/mysql

    #command: sh /home/usr/ssl_setup
    
  
volumes:
  sql:
  logs:
  config:
  sql_config:
