#!/bin/sh

#start container
docker-compose up -d

#kill container
docker-compose down

#configure ssl
docker exec -i ampache sh /home/usr/ssl_setup


#Open a terminal in a container
docker exec -it ampache bash

#Restore mySql from a file:
mysql -u ampache -p -h localhost ampache < /home/usr/backup.sql


#backup volume folders to tars
docker run --rm --volumes-from ampache -v /home/pi/ampache_docker/volume_backup:/backup busybox sh /backup/backup_script


#restore tar files from tars
docker run --rm --volumes-from ampache -v /home/pi/ampache_docker/volume_backup:/backup busybox sh /backup/restore_script

